# Dependabot configuration for automated dependency updates

version: 2
updates:
  # Enable version updates for pip (Python)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "cheesewhe"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "⬆️"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "cheesewhe"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "⬆️"

