name: Auto-Translate READMEs

# Автоматический перевод README.md на русский и китайский языки
# Запускается при изменении основного README.md файла

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
  workflow_dispatch:
    inputs:
      source_language:
        description: 'Source language (en, ru, zh-CN)'
        required: true
        default: 'en'
        type: choice
        options:
          - en
          - ru
          - zh-CN
      target_languages:
        description: 'Target languages (comma-separated: en,ru,zh-CN)'
        required: true
        default: 'ru,zh-CN'

jobs:
  translate-readmes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run translation
        env:
          SOURCE_LANG: ${{ github.event.inputs.source_language || 'en' }}
          TARGET_LANGS: ${{ github.event.inputs.target_languages || 'ru,zh-CN' }}
        run: |
          echo "🚀 Запуск перевода..."
          echo "📦 Установка языковых моделей для argostranslate..."
          python scripts/translate_readmes.py
      
      - name: Commit and push translations
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Добавляем переведенные файлы
          git add README.ru.md README.zh-CN.md
          
          # Проверяем, есть ли изменения
          if git diff --staged --quiet; then
            echo "✨ Нет изменений для коммита"
          else
            echo "📝 Коммит переводов..."
            git commit -m "🌍 chore: auto-update README translations [skip ci]"
            git push
            echo "✅ Переводы успешно загружены!"
          fi
